Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # Controller VM
  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network :private_network, ip: "192.168.56.10"
  end

  # Node1 VM
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.56.11"
  end

  # Node2 VM
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.56.12"
  end
end